import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jaat Entrepreneurs | Professional Web Development Agency",
  description: "Jaat Entrepreneurs is a leading web development agency specializing in custom website design, e-commerce solutions, and digital marketing services. We help businesses establish a strong online presence with cutting-edge technology and proven strategies.",
  keywords: [
    "Jaat Entrepreneurs",
    "Nikhil Chaudhary",
    "Vikrant Rathi",
    "Web Development Agency",
    "Web Development Company",
    "Web Development Services",
    "Web Development Agency in India",
    "Web Development Agency in Meerut",
    "Custom Website Design",
    "Custom Website Development",
    "Website Design",
    "Website Development",
    "Mobile App Development",
    "Mobile App Development Services",
    "Mobile App Development Company",
    "Mobile App Development Agency",
    "Mobile App Development Agency in India",
    "Mobile App Development Agency in Meerut",
    "E-commerce Development",
    "E-commerce Development Services",
    "E-commerce Development Company",
    "E-commerce Development Agency",
    "WordPress Development",
    "React Development",
    "Next.js Development",
    "Full Stack Development",
    "UI/UX Design",
    "Responsive Web Design",
    "Mobile App Development",
    "Progressive Web Apps",
    "Web Application Development",
    "API Development",
    "Database Development",
    "Cloud Solutions",
    "Digital Marketing",
    "SEO Services",
    "Social Media Marketing",
    "Content Marketing",
    "Email Marketing",
    "PPC Advertising",
    "Analytics & Reporting",
    "Business Website",
    "Corporate Website",
    "Portfolio Website",
    "Landing Page Design",
    "Website Maintenance",
    "Website Hosting",
    "Website Security",
    "Performance Optimization",
    "Custom Software Development",
    "Enterprise Solutions",
    "SaaS Development",
    "CMS Development",
    "Headless CMS",
    "GraphQL Development",
    "REST API Development",
    "Microservices Architecture",
    "DevOps Services",
    "CI/CD Implementation",
    "Cloud Migration",
    "AWS Solutions",
    "Azure Services",
    "Google Cloud Platform",
    "Serverless Architecture",
    "Blockchain Development",
    "Smart Contract Development",
    "NFT Development",
    "Web3 Development",
    "AI Integration",
    "Machine Learning Solutions",
    "Chatbot Development",
    "Voice Assistant Development",
    "IoT Development",
    "Mobile-First Design",
    "Cross-Platform Development",
    "Native App Development",
    "Hybrid App Development",
    "App Store Optimization",
    "App Maintenance",
    "App Security",
    "App Performance",
    "App Analytics",
    "App Testing",
    "Quality Assurance",
    "User Acceptance Testing",
    "Automated Testing",
    "Load Testing",
    "Security Testing",
    "Penetration Testing",
    "Vulnerability Assessment",
    "Code Review",
    "Technical Documentation",
    "API Documentation",
    "System Architecture",
    "Database Design",
    "Data Migration",
    "Data Analytics",
    "Business Intelligence",
    "Data Visualization",
    "Custom Dashboard Development",
    "Real-time Analytics",
    "Predictive Analytics",
    "Big Data Solutions",
    "Data Warehousing",
    "ETL Development",
    "Data Integration",
    "Data Security",
    "Data Privacy",
    "GDPR Compliance",
    "HIPAA Compliance",
    "PCI Compliance",
    "ISO 27001",
    "SOC 2 Compliance",
    "Cybersecurity Services",
    "Network Security",
    "Application Security",
    "Cloud Security",
    "Security Monitoring",
    "Incident Response",
    "Disaster Recovery",
    "Business Continuity",
    "IT Consulting",
    "Technology Strategy",
    "Digital Transformation",
    "IT Infrastructure",
    "System Integration",
    "Legacy System Modernization",
    "Technology Stack Selection",
    "Vendor Management",
    "Project Management",
    "Agile Development",
    "Scrum Methodology",
    "Kanban Implementation",
    "DevOps Culture",
    "Continuous Integration",
    "Continuous Deployment",
    "Infrastructure as Code",
    "Containerization",
    "Docker Development",
    "Kubernetes Orchestration",
    "Serverless Computing",
    "Function as a Service",
    "Backend as a Service",
    "Frontend Development",
    "Backend Development",
    "Full-Stack Development",
    "MEAN Stack",
    "MERN Stack",
    "LAMP Stack",
    "JAMstack",
    "Static Site Generation",
    "Server-Side Rendering",
    "Client-Side Rendering",
    "Progressive Enhancement",
    "Graceful Degradation",
    "Web Accessibility",
    "WCAG Compliance",
    "ARIA Implementation",
    "Semantic HTML",
    "CSS Architecture",
    "CSS-in-JS",
    "CSS Modules",
    "Styled Components",
    "Tailwind CSS",
    "Bootstrap Development",
    "Material Design",
    "Design Systems",
    "Component Libraries",
    "UI Component Development",
    "Custom UI Development",
    "Animation Development",
    "Motion Design",
    "Interactive Design",
    "User Experience Design",
    "User Interface Design",
    "Information Architecture",
    "Wireframing",
    "Prototyping",
    "User Research",
    "Usability Testing",
    "A/B Testing",
    "Conversion Rate Optimization",
    "User Flow Optimization",
    "Customer Journey Mapping",
    "Service Design",
    "Design Thinking",
    "Human-Centered Design",
    "Design Sprint",
    "Design Workshop",
    "Design System Development",
    "Brand Identity Design",
    "Visual Design",
    "Graphic Design",
    "Logo Design",
    "Icon Design",
    "Illustration",
    "Typography",
    "Color Theory",
    "Layout Design",
    "Grid Systems",
    "Responsive Design",
    "Adaptive Design",
    "Mobile Design",
    "Tablet Design",
    "Desktop Design",
    "Print Design",
    "Packaging Design",
    "Product Design",
    "Industrial Design",
    "Fashion Design",
    "Interior Design",
    "Architectural Design",
    "Urban Design",
    "Landscape Design",
    "Environmental Design",
    "Sustainable Design",
    "Green Design",
    "Eco-Friendly Design",
    "Biophilic Design",
    "Universal Design",
    "Inclusive Design",
    "Accessible Design",
    "Design for All",
    "Design for Good",
    "Social Impact Design",
    "Humanitarian Design",
    "Design Education",
    "Design Training",
    "Design Mentoring",
    "Design Coaching",
    "Design Consulting",
    "Design Strategy",
    "Design Management",
    "Performance Optimization"
  ],
  authors: [{ name: "Jaat Entrepreneurs", url: "https://jaatentrepreneurs.com" }],
  creator: "Jaat Entrepreneurs",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
